#!/bin/bash

for s in 4 16 32
do
	for h in 0 60 120 180 240
	do
		for n in 8 16 32
		do
			python AE_in_64x64x1_out_32x32x1.py --smoothing $s --horizon $h --nf $n
			sleep 30s
			python AE_in_64x64x2_out_32x32x1.py --smoothing $s --horizon $h --nf $n
			sleep 30s
			python AE_in_64x64x2_out_64x64x1.py --smoothing $s --horizon $h --nf $n
			sleep 30s
		done
	done
done


